import { StyleSheet } from "react-native";
import { color } from "../../assets/colors/theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "start",
    alignItems: "start",
    marginLeft: 10,
    marginRight: 12,
    marginTop: "10%",
    marginBottom: "5%",
    padding: 15,
    backgroundColor: color.neutral[200],
    borderRadius: 20,
    height: 200,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,

    elevation: 4,
  },
  heading: {
    fontSize: 20,
    color: color.fontcolor,
    fontWeight: "500",
    marginBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: color.neutral[300],
    paddingBottom: 10,
  },
  textlbl: {
    fontSize: 16,
    color: color.fontcolor,
    fontWeight: "500",
    marginBottom: 10,
  },
  ddView: {
    marginBottom: 20,
  },
  btn: {
    padding: 15,
    borderWidth: 1,
    justifyContent: "center",
    alignItems: "center",
    width: "75%",
    borderColor: color.primary,
    backgroundColor: color.primary,
    borderRadius: 15,
    alignSelf: "center",
  },
  btntext: {
    color: color.white,
    fontWeight: "500",
    fontSize: 20,
  },

  questionContainer: {
    flex: 1,
    backgroundColor: color.white,
    padding: 25,
    // margin: 15,
    justifyContent: "start",
    alignItems: "start",
    borderRadius: 12,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,

    elevation: 4,
  },
  quesLbl: {
    color: color.secondary,
    fontSize: 13,
    fontWeight: "600",
    marginBottom: 20,
  },
  questionText: {
    color: color.fontcolor,
    fontSize: 22,
    fontWeight: "500",
    marginBottom: 30,
  },
  answerContainer: {
    // backgroundColor:color.neutral[200],
    borderColor: color.neutral[300],
    borderWidth: 1,
    padding: 18,
    borderRadius: 10,
    marginBottom: 15,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    // shadowColor: "#000",
    // shadowOffset: {
    //   width: 0,
    //   height: 1,
    // },
    // shadowOpacity: 0.22,
    // shadowRadius: 1,

    // elevation: 1,
  },
  optionText: {
    color: color.fontcolor,
    fontSize: 15,
    fontWeight: "500",
    width: "80%",
  },

  nextContainer: {
    backgroundColor: color.primary,
    width: "30%",
    alignSelf: "flex-end",
    justifyContent: "flex-end",
    alignItems: "center",
    marginTop: 25,
    borderRadius: 10,
    // alignSelf:'flex-end',
  },
  nextText: {
    color: color.white,
    fontSize: 20,
    fontWeight: "500",
    padding: 10,
  },
  btnView: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  pressedOption: {
    borderColor: color.secondary,
    backgroundColor: "rgb(234,224,255)",
    borderWidth: 1,
    padding: 18,
    borderRadius: 10,
    marginBottom: 15,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
  },
  errorOption: {
    borderColor: color.danger,
    backgroundColor: color.secondary,
    borderWidth: 1,
    padding: 18,
    borderRadius: 10,
    marginBottom: 15,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
  },
  pressedText: {
    color: color.black,
    fontSize: 15,
    fontWeight: "500",
    width: "80%",
  },
  correctOption: {
    backgroundColor: color.success,
    padding: 18,
    borderRadius: 10,
    marginBottom: 15,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,

    elevation: 1,
  },
  correctText: {
    color: color.white,
    fontSize: 18,
    fontWeight: "500",
  },
});
