import { StyleSheet } from "react-native";
import { color } from "../../assets/colors/theme";

export const styles = StyleSheet.create({
    container:{
        flex:1
    },
    profileCard:{
        margin:'3%',
        padding:'2%',
        backgroundColor:color.white,
        borderRadius:12,
        flexDirection:'row',
    },
    profileCardBottomContainer:{
        margin:'3%',
        padding:'2%',
        backgroundColor:color.white,
        borderRadius:12,
    },
    profileCardBottom:{
        paddingVertical:12,
        flexDirection:'row',
        justifyContent:'space-between',
        borderBottomWidth:0.8,
        borderBottomColor:color.neutral[300]
    },
    profileCardBottomLast:{
        paddingVertical:12,
        flexDirection:'row',
        justifyContent:'space-between',
    },
    profileImage:{
        width:80,
        height:80,
        borderRadius:40,
        backgroundColor:color.secondary,
        justifyContent:'center',
        alignItems:'center',
        marginRight:'5%'
    },
    profileImageText:{
        color:color.white,
        fontSize:45,
        fontWeight:'500'
    },
    nameContainer:{
        justifyContent:'center',
        alignItems:'flex-start',
        rowGap:5,
        width:250
    },
    nameText:{
        color:color.fontcolor,
        fontSize:20,
        fontWeight:'500'
    },
    emailText:{
        color:color.neutral[500],
        fontSize:15,
    },
    iconContainer:{
        flexDirection:'row',
        justifyContent:'center',
        alignItems:'center',
    },
    icon:{
        marginRight:10
    },
    bottomText:{
        fontWeight:'400',
        marginLeft:12,
        fontSize:17
    }
})